# Modified from https://github.com/cpp-linter/cpp-linter-action/blob/main/.github/workflows/cpp-linter.yml
name: cpp-linter

on: 
  push:
    paths:
      - "thprac/src/thprac/*"
  pull_request:
    paths:
      - "thprac/src/thprac/*"

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cpp-linter/cpp-linter-action@main
        id: linter
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          files-changed-only: true
          thread-comments: false

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed != 0
        run: |
          echo "some linter checks failed. ${{ steps.linter.outputs.checks-failed }}"
        # for actual deployment
        # run: exit 1
